# Generated by Django 4.0 on 2021-12-18 14:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_header_sub_links_linkstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MediaTitle', models.CharField(max_length=100, verbose_name='تیتر مقاله')),
                ('MediaBody', ckeditor_uploader.fields.RichTextUploadingField(default='Body', null=True, verbose_name='متن مقاله')),
                ('MediaStatus', models.CharField(choices=[('Publish', 'انتشار'), ('Draft', 'پیش نویس')], max_length=10, null=True, verbose_name='وضعیت')),
            ],
        ),
    ]
