# Generated by Django 4.0 on 2021-12-19 07:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='MediaAddress',
            field=models.CharField(max_length=100, null=True, verbose_name='لینک ویدئو'),
        ),
        migrations.AlterField(
            model_name='header',
            name='HeaderDescription',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات بالای سایت'),
        ),
        migrations.AlterField(
            model_name='links',
            name='LinkAddress',
            field=models.CharField(max_length=1000, null=True, verbose_name='آدرس لینک'),
        ),
        migrations.AlterField(
            model_name='links',
            name='LinkName',
            field=models.CharField(max_length=100, null=True, verbose_name='نام لینک'),
        ),
        migrations.AlterField(
            model_name='media',
            name='MediaTitle',
            field=models.CharField(max_length=100, verbose_name='تیتر ویدئو'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='SubDescription',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات متن سایت'),
        ),
    ]
