# Generated by Django 4.0 on 2021-12-18 10:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleSlug',
            field=models.SlugField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='ArticleTitle',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='ArtileThumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
