# Generated by Django 4.0 on 2021-12-18 10:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutme_contact_projects_support_remove_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleSlug',
            field=models.SlugField(default='آدرس', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleTitle',
            field=models.CharField(default='تیتر', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArtileThumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
