# Generated by Django 4.0 on 2021-12-18 10:56

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_article_articlebody_alter_article_articledate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleSlug',
            field=models.SlugField(max_length=100, verbose_name='آدرس کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleTitle',
            field=models.CharField(max_length=100, verbose_name='تیتر مقاله'),
        ),
    ]
