# Generated by Django 4.0 on 2021-12-18 10:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_article_articlebody_alter_article_articleslug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Body'),
        ),
    ]
