# Generated by Django 4.0 on 2021-12-18 10:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_article_articlebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Body', verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleDate',
            field=models.DateField(verbose_name='تاریخ'),
        ),
    ]
