# Generated by Django 4.0 on 2021-12-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_article_articlebody_alter_article_articledate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ArticleBody',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ArticleDate',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ArticleSlug',
        ),
        migrations.RemoveField(
            model_name='article',
            name='ArtileThumbnail',
        ),
    ]
