# Generated by Django 4.0 on 2021-12-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_article_articlebody_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleSlug',
            field=models.SlugField(null=True, verbose_name='آدرس کوتاه'),
        ),
    ]
