# Generated by Django 4.0 on 2021-12-18 11:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_article_articlebody_article_articledate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='AboutmeBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='AboutmeImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Body', null=True, verbose_name='متن مقاله'),
        ),
    ]
