# Generated by Django 4.0 on 2021-12-18 11:12

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_aboutme_aboutmebody_aboutme_aboutmeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleDiscription',
            field=models.TextField(null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ContactDescription',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='تویحات'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectDescription',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات پروژه'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر پروژه'),
        ),
        migrations.AddField(
            model_name='support',
            name='SupportDescription',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='توضیحات پروژه'),
        ),
        migrations.AddField(
            model_name='support',
            name='SupportImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='تصویر پروژه'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='AboutmeBody',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات'),
        ),
    ]
