# Generated by Django 4.0 on 2021-12-18 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_article_articlediscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ArticleStatus',
            field=models.CharField(choices=[('Publish', 'انتشار'), ('Draft', 'پیش نویس')], max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='projects',
            name='ProjectStatus',
            field=models.CharField(choices=[('Publish', 'انتشار'), ('Draft', 'پیش نویس')], max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='support',
            name='ArticleStatus',
            field=models.CharField(choices=[('Publish', 'انتشار'), ('Draft', 'پیش نویس')], max_length=10, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ArticleDate',
            field=models.DateField(default=datetime.datetime(2021, 12, 18, 11, 22, 13, 286387, tzinfo=utc), verbose_name='تاریخ'),
        ),
    ]
