# Generated by Django 4.0 on 2021-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_article_articledate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ProjectName',
            field=models.CharField(max_length=100, null=True, verbose_name='نام پروژه'),
        ),
    ]
