# Generated by Django 4.0 on 2021-12-18 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_projects_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
