# Generated by Django 4.0 on 2021-12-18 14:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_article_articledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='SupportDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات '),
        ),
    ]
