# Generated by Django 4.0 on 2021-12-18 14:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_support_supportdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='ProjectDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='توضیحات پروژه'),
        ),
    ]
