# Generated by Django 4.0 on 2021-12-19 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_projects_projectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ProjectDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
    ]
