# Generated by Django 4.0 on 2021-12-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_projects_projectdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='ArticleStatus',
            new_name='SupportStatus',
        ),
    ]
