# Generated by Django 4.0 on 2021-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_rename_articlestatus_support_supportstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='SupportDate',
            field=models.DateField(null=True, verbose_name='تاریخ'),
        ),
    ]
