# Generated by Django 4.0 on 2021-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_support_supportdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryTitle', models.CharField(max_length=100, verbose_name='دسته')),
                ('CategorySlug', models.SlugField(null=True, verbose_name='آدرس کوتاه')),
                ('CategoryStatus', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
            ],
        ),
    ]
