# Generated by Django 4.0 on 2021-12-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_article_articlecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleCategory',
            field=models.ManyToManyField(related_name='articlecategory', to='pages.Category', verbose_name='دسته بندی'),
        ),
    ]
