# Generated by Django 4.0.1 on 2022-02-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_article_articlecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ParentCategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.category', verbose_name='دسته مادر'),
        ),
    ]
